

USE WEBBANDONGHO;
CREATE DATABASE WEBBANDONGHO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `NguoiDung` (
  `NguoiDungID` INT PRIMARY KEY AUTO_INCREMENT,
  `HoTen` VARCHAR(100) CHARACTER SET utf8mb4,
  `MatKhau` VARCHAR(50),
  `GioiTinh` VARCHAR(3),
  `Email` VARCHAR(100) UNIQUE,
  `DienThoai` VARCHAR(15),
  `VaiTro` VARCHAR(50),
  `NgayTao` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `NgayCapNhat` DATETIME
);
ALTER TABLE NguoiDung
MODIFY COLUMN MatKhau VARCHAR(255);

CREATE TABLE `LoaiHang` (
  `LoaiHangID` INT PRIMARY KEY AUTO_INCREMENT,
  `TenLoai` VARCHAR(100) CHARACTER SET utf8mb4
);

CREATE TABLE `HangDongHo` (
  `HangID` INT PRIMARY KEY AUTO_INCREMENT,
  `TenHang` VARCHAR(100) CHARACTER SET utf8mb4
);

CREATE TABLE `SanPham` (
  `SanPhamID` INT PRIMARY KEY AUTO_INCREMENT,
  `LoaiHangID` INT,
  `HangID` INT,
  `TenSanPham` VARCHAR(100) CHARACTER SET utf8mb4,
  `HinhAnh` VARCHAR(255),
  `MoTa` VARCHAR(255) CHARACTER SET utf8mb4,
  `MoTaChiTiet` TEXT CHARACTER SET utf8mb4,
  `SoLuotDanhGia` INT DEFAULT 0,
  `TongSao` INT DEFAULT 0,
  `GiaBan` FLOAT,
  `GiaGoc` FLOAT,
  `SoLuongTon` INT DEFAULT 0,
  `LuotBan` INT DEFAULT 0,
  `NgayTao` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `NgayCapNhat` DATETIME

);

CREATE TABLE `ThongSoKyThuat` (
  `ThongSoKyThuatID` INT PRIMARY KEY AUTO_INCREMENT,
  `SanPhamID` INT,
  `DuongKinhMat` VARCHAR(50),
  `ChatLieuDay` VARCHAR(100),
  `ChatLieuVo` VARCHAR(100),
  `KhangNuoc` VARCHAR(50),
  `LoaiMay` VARCHAR(100),
  `NguonGoc` VARCHAR(100),
  `TrongLuong` VARCHAR(50),
  `DoDay` VARCHAR(50),
  `BaoHanh` VARCHAR(100),
  `NgayTao` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `NgayCapNhat` DATETIME

);

CREATE TABLE `AnhSP` (
  `AnhSPID` INT PRIMARY KEY AUTO_INCREMENT,
  `SanPhamID` INT,
  `TenAnh` VARCHAR(100),
  `URLAnh` TEXT,
  `NgayTao` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `NgayCapNhat` DATETIME
 
);

CREATE TABLE `DonHang` (
  `DonHangID` INT PRIMARY KEY AUTO_INCREMENT,
  `NguoiDungID` INT,
  `NgayDatHang` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `TongSoLuong` INT,
  `ThanhTien` FLOAT,
  `TrangThai` VARCHAR(50),
  `NgayCapNhat` DATETIME

);

CREATE TABLE `ChiTietDonHang` (
  `ChiTietDHID` INT PRIMARY KEY AUTO_INCREMENT,
  `DonHangID` INT,
  `SanPhamID` INT,
  `SoLuong` INT,
  `DonGia` FLOAT,
  `TongTien` FLOAT,
  `NgayTao` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `NgayCapNhat` DATETIME

);
ALTER TABLE ChiTietDonHang
MODIFY NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;


CREATE TABLE `DanhGia` (
  `DanhGiaID` INT PRIMARY KEY AUTO_INCREMENT,
  `NguoiDungID` INT,
  `SanPhamID` INT,
  `NoiDung` VARCHAR(255),
  `DiemDanhGia` INT CHECK (`DiemDanhGia` BETWEEN 1 AND 5),
  `NgayDanhGia` DATETIME DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE `KhuyenMai` (
  `KhuyenMaiID` INT PRIMARY KEY AUTO_INCREMENT,
  `TenKhuyenMai` VARCHAR(100) NOT NULL,
  `MoTa` VARCHAR(255) NOT NULL,
  `PhanTramGiam` DECIMAL(5,2),
  `NgayBatDau` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `NgayKetThuc` DATETIME,
  `TrangThai` BIT DEFAULT 1
);

CREATE TABLE `SanPhamKhuyenMai` (
  `SanPhamKhuyenMaiID` INT PRIMARY KEY AUTO_INCREMENT,
  `SanPhamID` INT,
  `KhuyenMaiID` INT,
  `GhiChu` VARCHAR(255),
  `NgayTao` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `NgayCapNhat` DATETIME

);

CREATE TABLE `TinTuc` (
  `TinTucID` INT PRIMARY KEY AUTO_INCREMENT,
  `TieuDe` VARCHAR(255) NOT NULL,
  `NoiDung` VARCHAR(255) NOT NULL,
  `HinhAnh` TEXT,
  `NgayDang` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `TrangThai` BIT DEFAULT 1,
  `NgayCapNhat` DATETIME
);

CREATE TABLE `ChiTietTinTuc` (
  `ChiTietTinTucID` INT PRIMARY KEY AUTO_INCREMENT,
  `SanPhamID` INT NOT NULL,
  `TinTucID` INT NOT NULL,
  `NgayTao` DATETIME DEFAULT CURRENT_TIMESTAMP
  
);


ALTER TABLE `SanPham` 
  ADD FOREIGN KEY (`LoaiHangID`) REFERENCES `LoaiHang` (`LoaiHangID`) ON DELETE CASCADE;

ALTER TABLE `SanPham` 
  ADD FOREIGN KEY (`HangID`) REFERENCES `HangDongHo` (`HangID`) ON DELETE CASCADE;

ALTER TABLE `AnhSP` 
  ADD FOREIGN KEY (`SanPhamID`) REFERENCES `SanPham` (`SanPhamID`) ON DELETE CASCADE;

ALTER TABLE `DonHang` 
  ADD FOREIGN KEY (`NguoiDungID`) REFERENCES `NguoiDung` (`NguoiDungID`) ON DELETE CASCADE;

ALTER TABLE `ChiTietDonHang` 
  ADD FOREIGN KEY (`DonHangID`) REFERENCES `DonHang` (`DonHangID`) ON DELETE CASCADE;

ALTER TABLE `ChiTietDonHang` 
  ADD FOREIGN KEY (`SanPhamID`) REFERENCES `SanPham` (`SanPhamID`) ON DELETE CASCADE;

ALTER TABLE `DanhGia` 
  ADD FOREIGN KEY (`NguoiDungID`) REFERENCES `NguoiDung` (`NguoiDungID`) ON DELETE CASCADE;

ALTER TABLE `DanhGia` 
  ADD FOREIGN KEY (`SanPhamID`) REFERENCES `SanPham` (`SanPhamID`) ON DELETE CASCADE;

ALTER TABLE `SanPhamKhuyenMai` 
  ADD FOREIGN KEY (`SanPhamID`) REFERENCES `SanPham` (`SanPhamID`) ON DELETE CASCADE;

ALTER TABLE `SanPhamKhuyenMai` 
  ADD FOREIGN KEY (`KhuyenMaiID`) REFERENCES `KhuyenMai` (`KhuyenMaiID`) ON DELETE CASCADE;

ALTER TABLE `ChiTietTinTuc` 
  ADD FOREIGN KEY (`TinTucID`) REFERENCES `TinTuc` (`TinTucID`) ON DELETE CASCADE;

ALTER TABLE `ChiTietTinTuc` 
  ADD FOREIGN KEY (`SanPhamID`) REFERENCES `SanPham` (`SanPhamID`) ON DELETE CASCADE;

ALTER TABLE `ThongSoKyThuat` 
  ADD FOREIGN KEY (`SanPhamID`) REFERENCES `SanPham` (`SanPhamID`) ON DELETE CASCADE;
  
  

